// Auto-generated by refactor generate-barrel. Do not edit by hand.

export type { BattleCombatResult } from "./battle-system.ts";
export {
  advanceBattleCountdown,
  aimCannons,
  canFireOwnCannon,
  canPlayerFire,
  emitBattleCeaseIfTimerCrossed,
  fireNextReadyCannon,
  nextReadyCombined,
  setBattleCountdown,
  snapshotTerritory,
  tickBattlePhase,
} from "./battle-system.ts";
export {
  canPlacePiece,
  diffNewWalls,
  recheckTerritory,
  recomputeAllTerritory,
} from "./build-system.ts";
export {
  autoPlaceRound1Cannons,
  cannonSlotCost,
  cannonSlotsUsed,
  canPlaceCannon,
  effectivePlacementCost,
  filterActiveFiringCannons,
  hasAnyCannonPlacement,
  isCannonEnclosed,
  placeCannon,
  prepareControllerCannonPhase,
  resetCannonFacings,
} from "./cannon-system.ts";
export { createCastle } from "./castle-generation.ts";
export {
  executeCannonFire,
  executePlaceCannon,
  executePlacePiece,
} from "./game-actions.ts";
export {
  applyGameConfig,
  createGameFromSeed,
  enterBattlePhase,
  enterBuildPhase,
  enterCannonPhase,
  enterCastleReselectPhase,
  enterReselectPhase,
  enterSelectionPhase,
  isSelectionComplete,
  tickBuildPhase,
} from "./game-engine.ts";
export type { GameOverReason } from "./game-over.ts";
export { computeGameOutcome, eliminatePlayers } from "./game-over.ts";
export { tickGrunts } from "./grunt-movement.ts";
export { generateMap } from "./map-generation.ts";
export { applyCheckpointModifierTiles } from "./modifier-system.ts";
export {
  computeScoreDeltas,
  enterBuildSkippingBattle,
  finalizeBuildPhase,
  finalizeBuildVisuals,
  finalizeCastleConstruction,
  finalizeReselectedPlayers,
  prepareCastleWallsForPlayer,
  resetZoneState,
} from "./phase-setup.ts";
export {
  allSelectionsConfirmed,
  confirmTowerSelection,
  finishSelectionPhase,
  highlightTowerSelection,
} from "./selection.ts";
export {
  applyUpgradePicks,
  buildTimerBonus,
  canBuildThisFrame,
  shouldSkipBattle,
} from "./upgrade-system.ts";
export { consumeRapidEmplacement } from "./upgrades/rapid-emplacement.ts";
