// Auto-generated by refactor generate-barrel. Do not edit by hand.

export {
  advanceBattleCountdown,
  advanceCannonball,
  aimCannons,
  canFireOwnCannon,
  canPlayerFire,
  fireNextReadyCannon,
  getCountdownAnnouncement,
  nextReadyCombined,
  snapshotTerritory,
  tickBattlePhase,
} from "./battle-system.ts";
export {
  canPlacePiece,
  diffNewWalls,
  placePiece,
  recheckTerritory,
  recomputeAllTerritory,
} from "./build-system.ts";
export {
  autoPlaceRound1Cannons,
  cannonSlotCost,
  cannonSlotsUsed,
  canPlaceCannon,
  filterActiveFiringCannons,
  hasAnyCannonPlacement,
  isCannonEnclosed,
  placeCannon,
  prepareControllerCannonPhase,
  resetCannonFacings,
} from "./cannon-system.ts";
export { createCastle } from "./castle-generation.ts";
export { rehydrateComboTracker } from "./combo-system.ts";
export { executeCannonFire, executePlacePiece } from "./game-actions.ts";
export type { CannonPhaseEntry } from "./game-engine.ts";
export {
  applyGameConfig,
  createGameFromSeed,
  enterBattlePhase,
  enterBuildPhase,
  enterCannonPhase,
  enterCastleReselectPhase,
  enterReselectPhase,
  enterSelectionPhase,
  finalizeAndEnterCannonPhase,
  finishBuildPhase,
  isSelectionComplete,
  snapshotAndFinalizeForCannonPhase,
  tickBuildPhase,
} from "./game-engine.ts";
export { tickGrunts } from "./grunt-movement.ts";
export { generateMap } from "./map-generation.ts";
export {
  capturePrevBattleScene,
  snapshotCastles,
  snapshotEntities,
} from "./phase-banner.ts";
export {
  computeScoreDeltas,
  enterBuildSkippingBattle,
  finalizeReselectedPlayers,
  prepareCastleWallsForPlayer,
  resetZoneState,
} from "./phase-setup.ts";
export { applyCheckpointModifierTiles } from "./round-modifiers.ts";
export {
  allSelectionsConfirmed,
  confirmTowerSelection,
  finishSelectionPhase,
  highlightTowerSelection,
} from "./selection.ts";
export {
  applyUpgradePicks,
  canBuildThisFrame,
  shouldSkipBattle,
} from "./upgrade-system.ts";
