// Auto-generated by refactor generate-barrel. Do not edit by hand.

export {
  advanceBattleCountdown,
  advanceCannonball,
  aimCannons,
  applyImpactEvent,
  canFireOwnCannon,
  canPlayerFire,
  fireNextReadyCannon,
  getCountdownAnnouncement,
  nextReadyCombined,
  snapshotTerritory,
  tickBattleCombat,
} from "./battle-system.ts";
export {
  buildTimerMax,
  diffNewWalls,
  tickMasterBuilderLockout,
} from "./build-phase-helpers.ts";
export {
  applyPiecePlacement,
  canPlacePiece,
  placePiece,
  recheckTerritoryOnly,
  recomputeTerritoryFromWalls,
} from "./build-system.ts";
export {
  applyCannonPlacement,
  autoPlaceRound1Cannons,
  cannonSlotCost,
  cannonSlotsUsed,
  canPlaceCannon,
  filterActiveFiringCannons,
  hasAnyCannonPlacement,
  isCannonEnclosed,
  placeCannon,
  prepareControllerCannonPhase,
  resetCannonFacings,
} from "./cannon-system.ts";
export { createCastle } from "./castle-generation.ts";
export { createComboTracker, isCombosEnabled } from "./combo-system.ts";
export { executeCannonFire, executePlacePiece } from "./game-actions.ts";
export type { CannonPhaseEntry } from "./game-engine.ts";
export {
  applyGameConfig,
  createGameFromSeed,
  enterBattlePhase,
  enterBuildPhase,
  enterCannonPhase,
  enterCastleReselectPhase,
  enterReselectPhase,
  enterSelectionPhase,
  finalizeAndEnterCannonPhase,
  finishBuildPhase,
  isCeasefireActive,
  isSelectionComplete,
  markPlayerReselected,
  snapshotAndFinalizeForCannonPhase,
} from "./game-engine.ts";
export { tickGrunts } from "./grunt-movement.ts";
export { generateMap } from "./map-generation.ts";
export {
  capturePrevBattleScene,
  snapshotCastles,
  snapshotEntities,
} from "./phase-banner.ts";
export {
  computeScoreDeltas,
  enterBuildSkippingBattle,
  finalizeReselectedPlayers,
  prepareCastleWallsForPlayer,
  resetZoneState,
  setPhase,
} from "./phase-setup.ts";
export {
  reapplyHighTideTiles,
  reapplySinkholeTiles,
} from "./round-modifiers.ts";
export {
  allSelectionsConfirmed,
  confirmTowerSelection,
  finishSelectionPhase,
  highlightTowerSelection,
} from "./selection.ts";
export { applyUpgradePicks } from "./upgrade-pick.ts";
