import { deletePlayerWallsBatch } from "../shared/board-occupancy.ts";
import { FID } from "../shared/feature-defs.ts";
import { emitGameEvent, GAME_EVENT } from "../shared/game-event-bus.ts";
import {
  type AutoResolveDeps,
  shouldAutoResolve,
  type UpgradePickDialogState,
  type UpgradePickEntry,
} from "../shared/interaction-types.ts";
import type { ValidPlayerSlot } from "../shared/player-slot.ts";
import { isPlayerEliminated, isPlayerSeated } from "../shared/player-types.ts";
import {
  computeOutside,
  DIRS_8,
  isCannonAlive,
  packTile,
  unpackTile,
} from "../shared/spatial.ts";
import {
  type GameState,
  hasFeature,
  type UpgradeOfferTuple,
} from "../shared/types.ts";
import {
  IMPLEMENTED_UPGRADES,
  UID,
  type UpgradeId,
} from "../shared/upgrade-defs.ts";

interface CreateUpgradePickDeps extends AutoResolveDeps {
  readonly state: GameState;
}

/** First round that triggers upgrade picks (modern mode). */
const UPGRADE_FIRST_ROUND = 3;
/** Number of upgrade choices offered per pick. */
const OFFER_COUNT = 3;
/** Extra delay per auto-resolving entry so AI picks land one at a time,
 *  not all on the same frame. Applied by entry index in dialog.entries. */
const UPGRADE_PICK_STAGGER = 0.5;
/** Time between focus "steps" while an AI entry cycles through its offers
 *  during the delay. One step moves focus to the next card. */
const UPGRADE_PICK_CYCLE_STEP = 0.22;
/** Window at the end of the delay where the AI stops cycling and locks
 *  focus onto its final pick, so the reveal doesn't feel like a random snap. */
const UPGRADE_PICK_LOCK_IN = 0.35;
/** Auto-resolve delay before auto-picking (seconds). */
export const UPGRADE_PICK_AUTO_DELAY = 1.5;
/** Max time before force-picking for pending players (seconds). */
export const UPGRADE_PICK_MAX_TIMER = 15;

/** Create the pick dialog from pre-generated offers on GameState.
 *  Offers were generated by generateUpgradeOffers() in enterBuildFromBattle()
 *  using the synced RNG, so they're already deterministic.
 *  Returns null if picks are not applicable (classic mode, too early, no alive players). */
export function createUpgradePickDialog(
  deps: CreateUpgradePickDeps,
): UpgradePickDialogState | null {
  const { state } = deps;
  if (!state.modern?.pendingUpgradeOffers) return null;

  const entries: UpgradePickEntry[] = [];
  for (const [playerId, offers] of state.modern.pendingUpgradeOffers) {
    const autoResolve = shouldAutoResolve(playerId, deps);

    entries.push({
      playerId,
      offers,
      choice: null,
      autoResolve,
      autoTimer: 0,
      focusedCard: 0,
      pickedAtTimer: null,
      plannedChoice: null,
    });
  }

  if (entries.length === 0) return null;
  return { entries, timer: 0 };
}

/** Tick the upgrade pick dialog. Auto-resolve entries pick after a delay;
 *  max timer force-picks for all remaining entries.
 *  Returns true when all entries are resolved.
 *  @param dt — Delta time in seconds (not ms).
 *  @param autoDelay — Per-entry auto-resolve delay in seconds.
 *  @param maxTimer — Global force-resolve deadline in seconds.
 *  @param aiPick — Optional AI pick callback; when provided, auto-resolve
 *    entries use contextual selection instead of random. */
// Parallel structure with tickLifeLostDialog (life-lost.ts) — both loop entries for auto-resolve + force-resolve.
export function tickUpgradePickDialog(
  dialog: UpgradePickDialogState,
  dt: number,
  autoDelay: number,
  maxTimer: number,
  state?: GameState,
  aiPick?: (
    offers: readonly [UpgradeId, UpgradeId, UpgradeId],
    playerId: ValidPlayerSlot,
  ) => UpgradeId,
): boolean {
  dialog.timer += dt;

  // Auto-resolve pending entries. Effective delay is staggered by entry
  // index so picks land sequentially. Each AI entry cycles focus through
  // its offers during the delay, then locks onto its final pick for the
  // last LOCK_IN window so the commit doesn't look like a random jump.
  for (let entryIdx = 0; entryIdx < dialog.entries.length; entryIdx++) {
    const entry = dialog.entries[entryIdx]!;
    if (entry.choice !== null) continue;
    if (!entry.autoResolve) continue;

    entry.autoTimer += dt;
    const effectiveDelay = autoDelay + entryIdx * UPGRADE_PICK_STAGGER;
    const lockInStart = effectiveDelay - UPGRADE_PICK_LOCK_IN;

    if (entry.autoTimer >= effectiveDelay) {
      const pick =
        entry.plannedChoice ??
        (aiPick
          ? aiPick(entry.offers, entry.playerId)
          : randomPickUpgrade(entry.offers, state));
      entry.choice = pick;
      entry.focusedCard = entry.offers.indexOf(pick);
      entry.pickedAtTimer = dialog.timer;
    } else if (entry.autoTimer >= lockInStart) {
      if (entry.plannedChoice === null) {
        entry.plannedChoice = aiPick
          ? aiPick(entry.offers, entry.playerId)
          : randomPickUpgrade(entry.offers, state);
      }
      entry.focusedCard = entry.offers.indexOf(entry.plannedChoice);
    } else {
      entry.focusedCard =
        Math.floor(entry.autoTimer / UPGRADE_PICK_CYCLE_STEP) %
        entry.offers.length;
    }
  }

  // Max timer — force-pick for anyone still pending
  if (dialog.timer >= maxTimer) {
    for (const entry of dialog.entries) {
      if (entry.choice === null) {
        const pick =
          entry.plannedChoice ?? randomPickUpgrade(entry.offers, state);
        entry.choice = pick;
        entry.focusedCard = entry.offers.indexOf(pick);
        entry.pickedAtTimer = dialog.timer;
      }
    }
  }

  return dialog.entries.every((entry) => entry.choice !== null);
}

/** Navigate focus left/right within a pending entry's offers. */
export function moveUpgradePickFocus(
  entry: UpgradePickEntry,
  dir: number,
): void {
  entry.focusedCard =
    (entry.focusedCard + dir + entry.offers.length) % entry.offers.length;
}

/** Resolve a pending entry by picking a specific card. Returns the chosen upgrade. */
export function resolveUpgradePickEntry(
  entry: UpgradePickEntry,
  cardIdx: number,
  dialogTimer: number,
): UpgradeId {
  entry.focusedCard = cardIdx;
  const choice = entry.offers[cardIdx]!;
  entry.choice = choice;
  entry.pickedAtTimer = dialogTimer;
  return choice;
}

/** Apply all picked upgrades to player state. */
export function applyUpgradePicks(
  state: GameState,
  dialog: UpgradePickDialogState,
): void {
  let secondWind = false;
  let clearTheField = false;
  let demolition = false;
  const reclamationPlayers: ValidPlayerSlot[] = [];
  for (const entry of dialog.entries) {
    if (entry.choice === null) continue;
    const player = state.players[entry.playerId];
    if (!player) continue;
    player.upgrades.set(entry.choice, 1);
    emitGameEvent(state.bus, GAME_EVENT.UPGRADE_PICKED, {
      playerId: entry.playerId,
      upgradeId: entry.choice,
    });
    if (entry.choice === UID.SECOND_WIND) secondWind = true;
    if (entry.choice === UID.CLEAR_THE_FIELD) clearTheField = true;
    if (entry.choice === UID.DEMOLITION) demolition = true;
    if (entry.choice === UID.RECLAMATION)
      reclamationPlayers.push(entry.playerId);
  }
  if (secondWind) {
    for (let idx = 0; idx < state.towerAlive.length; idx++) {
      state.towerAlive[idx] = true;
    }
    state.towerPendingRevive.clear();
  }
  if (clearTheField) {
    state.grunts.length = 0;
  }
  if (demolition) {
    stripInnerWalls(state);
  }
  for (const pid of reclamationPlayers) {
    const player = state.players[pid];
    if (player) {
      player.cannons = player.cannons.filter(isCannonAlive);
    }
  }
}

/** Generate upgrade offers for all alive players. Uses state.rng for determinism.
 *  Called from enterBuildFromBattle so the RNG is consumed before the
 *  BUILD_START checkpoint is sent. Returns null if not applicable. */
export function generateUpgradeOffers(
  state: GameState,
): Map<ValidPlayerSlot, UpgradeOfferTuple> | null {
  if (!hasFeature(state, FID.UPGRADES)) return null;
  if (state.round < UPGRADE_FIRST_ROUND) return null;

  const offers = new Map<ValidPlayerSlot, UpgradeOfferTuple>();
  for (const player of state.players) {
    if (!isPlayerSeated(player)) continue;
    offers.set(player.id, drawOffers(state));
  }
  return offers.size > 0 ? offers : null;
}

/** All upgrades last one round — clear damaged-wall markers and upgrade maps. */
export function resetPlayerUpgrades(state: GameState): void {
  for (const player of state.players) {
    player.damagedWalls.clear();
    player.upgrades.clear();
  }
}

/** Pick a random offer using the synced RNG. */
function randomPickUpgrade(
  offers: readonly [UpgradeId, UpgradeId, UpgradeId],
  state?: GameState,
): UpgradeId {
  if (!state) return offers[0];
  return offers[Math.floor(state.rng.next() * offers.length)]!;
}

/** Draw N unique upgrades from the implemented pool using state.rng. */
function drawOffers(state: GameState): [UpgradeId, UpgradeId, UpgradeId] {
  const pool = [...IMPLEMENTED_UPGRADES];
  const picked: UpgradeId[] = [];

  for (let i = 0; i < OFFER_COUNT && pool.length > 0; i++) {
    const totalWeight = pool.reduce((sum, def) => sum + def.weight, 0);
    let roll = state.rng.next() * totalWeight;
    let chosenIdx = pool.length - 1;
    for (let poolIdx = 0; poolIdx < pool.length; poolIdx++) {
      roll -= pool[poolIdx]!.weight;
      if (roll <= 0) {
        chosenIdx = poolIdx;
        break;
      }
    }
    picked.push(pool[chosenIdx]!.id);
    pool.splice(chosenIdx, 1);
  }

  return picked as [UpgradeId, UpgradeId, UpgradeId];
}

/** Strip non-load-bearing walls from all players.
 *  A wall is "inner" (safe to remove) if none of its 8-dir neighbors are
 *  outside (reachable from map edges). Enclosures remain intact; thick walls
 *  are thinned to a single-tile shell. Can merge adjacent castles.
 *  Uses deletePlayerWallsBatch (skips markWallsDirty) — interior is rechecked
 *  at the next piece placement or end-of-build via recheckTerritoryOnly. */
function stripInnerWalls(state: GameState): void {
  for (const player of state.players) {
    if (isPlayerEliminated(player)) continue;
    if (player.walls.size === 0) continue;
    const outside = computeOutside(player.walls);
    const inner: number[] = [];
    for (const key of player.walls) {
      const { r, c } = unpackTile(key);
      let loadBearing = false;
      for (const [dr, dc] of DIRS_8) {
        if (outside.has(packTile(r + dr, c + dc))) {
          loadBearing = true;
          break;
        }
      }
      if (!loadBearing) inner.push(key);
    }
    if (inner.length > 0) deletePlayerWallsBatch(player, inner);
  }
}
