import { FID } from "../shared/feature-defs.ts";
import {
  type AutoResolveDeps,
  shouldAutoResolve,
  type UpgradePickDialogState,
  type UpgradePickEntry,
} from "../shared/interaction-types.ts";
import type { ValidPlayerSlot } from "../shared/player-slot.ts";
import {
  type GameState,
  hasFeature,
  type UpgradeOfferTuple,
} from "../shared/types.ts";
import {
  IMPLEMENTED_UPGRADES,
  UID,
  type UpgradeId,
} from "../shared/upgrade-defs.ts";

interface CreateUpgradePickDeps extends AutoResolveDeps {
  readonly state: GameState;
}

/** First round that triggers upgrade picks (modern mode). */
const UPGRADE_FIRST_ROUND = 3;
/** Number of upgrade choices offered per pick. */
const OFFER_COUNT = 3;
/** Auto-resolve delay before auto-picking (seconds). */
export const UPGRADE_PICK_AUTO_DELAY = 1.5;
/** Max time before force-picking for pending players (seconds). */
export const UPGRADE_PICK_MAX_TIMER = 15;

/** Create the pick dialog from pre-generated offers on GameState.
 *  Offers were generated by generateUpgradeOffers() in enterBuildFromBattle()
 *  using the synced RNG, so they're already deterministic.
 *  Returns null if picks are not applicable (classic mode, too early, no alive players). */
export function createUpgradePickDialog(
  deps: CreateUpgradePickDeps,
): UpgradePickDialogState | null {
  const { state } = deps;
  if (!state.modern?.pendingUpgradeOffers) return null;

  const entries: UpgradePickEntry[] = [];
  for (const [playerId, offers] of state.modern.pendingUpgradeOffers) {
    const autoResolve = shouldAutoResolve(playerId, deps);

    entries.push({
      playerId,
      offers,
      choice: null,
      autoResolve,
      autoTimer: 0,
      focusedCard: 0,
    });
  }

  if (entries.length === 0) return null;
  return { entries, timer: 0 };
}

/** Tick the upgrade pick dialog. Auto-resolve entries pick after a delay;
 *  max timer force-picks for all remaining entries.
 *  Returns true when all entries are resolved.
 *  @param aiPick — Optional AI pick callback; when provided, auto-resolve
 *    entries use contextual selection instead of random. */
// Parallel structure with tickLifeLostDialog (life-lost.ts) — both loop entries for auto-resolve + force-resolve.
export function tickUpgradePickDialog(
  dialog: UpgradePickDialogState,
  dt: number,
  autoDelay: number,
  maxTimer: number,
  state?: GameState,
  aiPick?: (
    offers: readonly [UpgradeId, UpgradeId, UpgradeId],
    playerId: ValidPlayerSlot,
  ) => UpgradeId,
): boolean {
  dialog.timer += dt;

  // Auto-resolve pending entries
  for (const entry of dialog.entries) {
    if (entry.choice !== null) continue;
    if (entry.autoResolve) {
      entry.autoTimer += dt;
      if (entry.autoTimer >= autoDelay) {
        entry.choice = aiPick
          ? aiPick(entry.offers, entry.playerId)
          : randomPickUpgrade(entry.offers);
      }
    }
  }

  // Max timer — force-pick for anyone still pending
  if (dialog.timer >= maxTimer) {
    for (const entry of dialog.entries) {
      if (entry.choice === null) {
        entry.choice = randomPickUpgrade(entry.offers, state);
      }
    }
  }

  return dialog.entries.every((entry) => entry.choice !== null);
}

/** Navigate focus left/right within a pending entry's offers. */
export function moveUpgradePickFocus(
  entry: UpgradePickEntry,
  dir: number,
): void {
  entry.focusedCard =
    (entry.focusedCard + dir + entry.offers.length) % entry.offers.length;
}

/** Resolve a pending entry by picking a specific card. Returns the chosen upgrade. */
export function resolveUpgradePickEntry(
  entry: UpgradePickEntry,
  cardIdx: number,
): UpgradeId {
  entry.focusedCard = cardIdx;
  const choice = entry.offers[cardIdx]!;
  entry.choice = choice;
  return choice;
}

/** Apply all picked upgrades to player state. */
export function applyUpgradePicks(
  state: GameState,
  dialog: UpgradePickDialogState,
): void {
  let secondWind = false;
  let clearTheField = false;
  for (const entry of dialog.entries) {
    if (entry.choice === null) continue;
    const player = state.players[entry.playerId];
    if (!player) continue;
    player.upgrades.set(entry.choice, 1);
    if (entry.choice === UID.SECOND_WIND) secondWind = true;
    if (entry.choice === UID.CLEAR_THE_FIELD) clearTheField = true;
  }
  if (secondWind) {
    for (let idx = 0; idx < state.towerAlive.length; idx++) {
      state.towerAlive[idx] = true;
    }
    state.towerPendingRevive.clear();
  }
  if (clearTheField) {
    state.grunts.length = 0;
    state.gruntSpawnQueue.length = 0;
  }
}

/** Generate upgrade offers for all alive players. Uses state.rng for determinism.
 *  Called from enterBuildFromBattle so the RNG is consumed before the
 *  BUILD_START checkpoint is sent. Returns null if not applicable. */
export function generateUpgradeOffers(
  state: GameState,
): Map<ValidPlayerSlot, UpgradeOfferTuple> | null {
  if (!hasFeature(state, FID.UPGRADES)) return null;
  if (state.round < UPGRADE_FIRST_ROUND) return null;

  const offers = new Map<ValidPlayerSlot, UpgradeOfferTuple>();
  for (const player of state.players) {
    if (player.eliminated || !player.homeTower) continue;
    offers.set(player.id, drawOffers(state));
  }
  return offers.size > 0 ? offers : null;
}

/** All upgrades last one round — clear damaged-wall markers and upgrade maps. */
export function resetPlayerUpgrades(state: GameState): void {
  for (const player of state.players) {
    player.damagedWalls.clear();
    player.upgrades.clear();
  }
}

/** Pick a random offer using the synced RNG. */
function randomPickUpgrade(
  offers: readonly [UpgradeId, UpgradeId, UpgradeId],
  state?: GameState,
): UpgradeId {
  if (!state) return offers[0];
  return offers[Math.floor(state.rng.next() * offers.length)]!;
}

/** Draw N unique upgrades from the implemented pool using state.rng. */
function drawOffers(state: GameState): [UpgradeId, UpgradeId, UpgradeId] {
  const pool = [...IMPLEMENTED_UPGRADES];
  const picked: UpgradeId[] = [];

  for (let i = 0; i < OFFER_COUNT && pool.length > 0; i++) {
    const totalWeight = pool.reduce((sum, def) => sum + def.weight, 0);
    let roll = state.rng.next() * totalWeight;
    let chosenIdx = pool.length - 1;
    for (let poolIdx = 0; poolIdx < pool.length; poolIdx++) {
      roll -= pool[poolIdx]!.weight;
      if (roll <= 0) {
        chosenIdx = poolIdx;
        break;
      }
    }
    picked.push(pool[chosenIdx]!.id);
    pool.splice(chosenIdx, 1);
  }

  return picked as [UpgradeId, UpgradeId, UpgradeId];
}
