/**
 * Upgrade-pick dialog primitives.
 *
 * Dialog state factory, tick, and focus/resolve helpers. Moved here from
 * game/ because they manage UI dialog state (focus, timers, per-entry
 * resolution), not game rules. The game rules (applyUpgradePicks,
 * generateUpgradeOffers, resetPlayerUpgrades) stay in game/upgrade-pick.ts
 * since they mutate game state based on resolved choices.
 *
 * Consumed by runtime-upgrade-pick.ts which wraps these into the dialog
 * subsystem.
 */

import type { GameState } from "../shared/core/types.ts";
import type { UpgradeId } from "../shared/core/upgrade-defs.ts";
import {
  type AutoResolveDeps,
  shouldAutoResolve,
  type UpgradePickDialogState,
  type UpgradePickEntry,
} from "../shared/ui/interaction-types.ts";
import { tickDialogWithFallback } from "./dialog-tick.ts";

interface CreateUpgradePickDeps extends AutoResolveDeps {
  readonly state: GameState;
}

/** Per-entry auto-resolve tick. Dispatched by the runtime to the owning
 *  controller (`controller.tickUpgradePick`). Callers close over the
 *  per-call GameState and `autoDelaySeconds` when wrapping. */
type ControllerUpgradePickTick = (
  entry: UpgradePickEntry,
  entryIdx: number,
) => void;

/** Force-pick fallback for max-timer expiry. Dispatched to the owning
 *  controller (`controller.forceUpgradePick`). */
type ControllerForceUpgradePick = (entry: UpgradePickEntry) => UpgradeId;

/** Create the pick dialog from pre-generated offers on GameState.
 *  Offers were generated by generateUpgradeOffers() in prepareNextRound()
 *  using the synced RNG, so they're already deterministic.
 *  Returns null if picks are not applicable (classic mode, too early, no alive players). */
export function createUpgradePickDialog(
  deps: CreateUpgradePickDeps,
): UpgradePickDialogState | null {
  const { state } = deps;
  if (!state.modern?.pendingUpgradeOffers) return null;

  const entries: UpgradePickEntry[] = [];
  for (const [playerId, offers] of state.modern.pendingUpgradeOffers) {
    const autoResolve = shouldAutoResolve(playerId, deps);

    entries.push({
      playerId,
      offers,
      choice: null,
      autoResolve,
      autoTimer: 0,
      focusedCard: 0,
      pickedAtTimer: null,
      plannedChoice: null,
    });
  }

  if (entries.length === 0) return null;
  return { entries, timer: 0 };
}

/** Tick the upgrade pick dialog.
 *
 *  Drives dialog-layer state only: increments `dialog.timer`, delegates
 *  each pending auto-resolve entry to the per-entry `tickEntry` callback,
 *  and applies the max-timer safety net by delegating to `forcePick`.
 *  Both callbacks dispatch to the controller that owns each slot.
 *
 *  Returns true when all entries are resolved.
 *
 *  @param dt — Delta time in seconds (not ms).
 *  @param maxTimer — Global force-resolve deadline in seconds.
 *  @param tickEntry — Per-entry tick (closed over state + autoDelay).
 *  @param forcePick — Max-timer force-pick (closed over state). */
// Shares the auto-resolve + force-resolve loop with tickLifeLostDialog via tickDialogWithFallback.
export function tickUpgradePickDialog(
  dialog: UpgradePickDialogState,
  dt: number,
  maxTimer: number,
  tickEntry: ControllerUpgradePickTick,
  forcePick: ControllerForceUpgradePick,
): boolean {
  return tickDialogWithFallback<UpgradePickEntry>({
    dialog,
    dt,
    maxTimer,
    isPending: (entry) => entry.choice === null,
    isAutoResolving: (entry) => entry.autoResolve,
    tickEntry: (entry, entryIdx) => {
      tickEntry(entry, entryIdx);
    },
    forceResolve: (entry) => {
      const pick = forcePick(entry);
      entry.choice = pick;
      entry.focusedCard = entry.offers.indexOf(pick);
      entry.pickedAtTimer = dialog.timer;
    },
  });
}

/** Navigate focus left/right within a pending entry's offers. */
export function moveUpgradePickFocus(
  entry: UpgradePickEntry,
  dir: number,
): void {
  entry.focusedCard =
    (entry.focusedCard + dir + entry.offers.length) % entry.offers.length;
}

/** Resolve a pending entry by picking a specific card. Returns the chosen upgrade. */
export function resolveUpgradePickEntry(
  entry: UpgradePickEntry,
  cardIdx: number,
  dialogTimer: number,
): UpgradeId {
  entry.focusedCard = cardIdx;
  const choice = entry.offers[cardIdx]!;
  entry.choice = choice;
  entry.pickedAtTimer = dialogTimer;
  return choice;
}
