/**
 * Upgrade-pick dialog primitives.
 *
 * Dialog state factory, tick, and focus/resolve helpers. Moved here from
 * game/ because they manage UI dialog state (focus, timers, per-entry
 * resolution), not game rules. The game rules (applyUpgradePicks,
 * generateUpgradeOffers, resetPlayerUpgrades) stay in game/upgrade-pick.ts
 * since they mutate game state based on resolved choices.
 *
 * Consumed by runtime-upgrade-pick.ts which wraps these into the dialog
 * subsystem.
 */

import type { GameState } from "../shared/types.ts";
import {
  type AutoResolveDeps,
  shouldAutoResolve,
  type UpgradePickDialogState,
  type UpgradePickEntry,
} from "../shared/ui/interaction-types.ts";
import type { UpgradeId } from "../shared/upgrade-defs.ts";

interface CreateUpgradePickDeps extends AutoResolveDeps {
  readonly state: GameState;
}

/** Per-entry auto-resolve tick. Injected by the runtime from ai/ so
 *  game/ stays decoupled from AI code — see `tickAiUpgradePickEntry` in
 *  `ai/ai-upgrade-pick.ts`. */
type AiUpgradePickTick = (
  entry: UpgradePickEntry,
  entryIdx: number,
  dt: number,
  autoDelay: number,
  dialogTimer: number,
) => void;

/** Force-pick fallback for max-timer expiry. Injected by the runtime
 *  from ai/ (same domain-decoupling reason) — see `forcePickUpgradeEntry`
 *  in `ai/ai-upgrade-pick.ts`. */
type ForceUpgradePick = (entry: UpgradePickEntry) => UpgradeId;

/** Create the pick dialog from pre-generated offers on GameState.
 *  Offers were generated by generateUpgradeOffers() in enterBuildFromBattle()
 *  using the synced RNG, so they're already deterministic.
 *  Returns null if picks are not applicable (classic mode, too early, no alive players). */
export function createUpgradePickDialog(
  deps: CreateUpgradePickDeps,
): UpgradePickDialogState | null {
  const { state } = deps;
  if (!state.modern?.pendingUpgradeOffers) return null;

  const entries: UpgradePickEntry[] = [];
  for (const [playerId, offers] of state.modern.pendingUpgradeOffers) {
    const autoResolve = shouldAutoResolve(playerId, deps);

    entries.push({
      playerId,
      offers,
      choice: null,
      autoResolve,
      autoTimer: 0,
      focusedCard: 0,
      pickedAtTimer: null,
      plannedChoice: null,
    });
  }

  if (entries.length === 0) return null;
  return { entries, timer: 0 };
}

/** Tick the upgrade pick dialog.
 *
 *  Drives dialog-layer state only: increments `dialog.timer`, delegates
 *  each pending auto-resolve entry to the injected `tickAiEntry` callback,
 *  and applies the max-timer safety net by delegating to `forcePick`
 *  (both callbacks live in `ai/ai-upgrade-pick.ts`).
 *
 *  Returns true when all entries are resolved.
 *
 *  @param dt — Delta time in seconds (not ms).
 *  @param autoDelay — Per-entry auto-resolve delay in seconds.
 *  @param maxTimer — Global force-resolve deadline in seconds.
 *  @param tickAiEntry — AI auto-resolve tick (closed over GameState).
 *  @param forcePick — Max-timer force-pick callback (closed over GameState). */
// Parallel structure with tickLifeLostDialog (runtime-life-lost-core.ts) — both loop entries for auto-resolve + force-resolve.
export function tickUpgradePickDialog(
  dialog: UpgradePickDialogState,
  dt: number,
  autoDelay: number,
  maxTimer: number,
  tickAiEntry: AiUpgradePickTick,
  forcePick: ForceUpgradePick,
): boolean {
  dialog.timer += dt;

  for (let entryIdx = 0; entryIdx < dialog.entries.length; entryIdx++) {
    const entry = dialog.entries[entryIdx]!;
    if (entry.choice !== null) continue;
    if (!entry.autoResolve) continue;
    tickAiEntry(entry, entryIdx, dt, autoDelay, dialog.timer);
  }

  if (dialog.timer >= maxTimer) {
    for (const entry of dialog.entries) {
      if (entry.choice === null) {
        const pick = forcePick(entry);
        entry.choice = pick;
        entry.focusedCard = entry.offers.indexOf(pick);
        entry.pickedAtTimer = dialog.timer;
      }
    }
  }

  return dialog.entries.every((entry) => entry.choice !== null);
}

/** Navigate focus left/right within a pending entry's offers. */
export function moveUpgradePickFocus(
  entry: UpgradePickEntry,
  dir: number,
): void {
  entry.focusedCard =
    (entry.focusedCard + dir + entry.offers.length) % entry.offers.length;
}

/** Resolve a pending entry by picking a specific card. Returns the chosen upgrade. */
export function resolveUpgradePickEntry(
  entry: UpgradePickEntry,
  cardIdx: number,
  dialogTimer: number,
): UpgradeId {
  entry.focusedCard = cardIdx;
  const choice = entry.offers[cardIdx]!;
  entry.choice = choice;
  entry.pickedAtTimer = dialogTimer;
  return choice;
}
