/**
 * Upgrade-pick dialog primitives — state factory, tick, focus/resolve
 * helpers. Lives in runtime/ because it manages UI dialog state (focus,
 * timers, per-entry resolution), not game rules. The rules
 * (applyUpgradePicks, generateUpgradeOffers, resetPlayerUpgrades) stay in
 * game/upgrade-system.ts since they mutate game state based on resolved
 * choices. Consumed by subsystems/upgrade-pick.ts.
 */

import type {
  AutoResolveDeps,
  UpgradePickDialogState,
  UpgradePickEntry,
} from "../../shared/core/dialog-state.ts";
import { shouldAutoResolve } from "../../shared/core/dialog-state.ts";
import type { ValidPlayerId } from "../../shared/core/player-slot.ts";
import type { GameState } from "../../shared/core/types.ts";
import type { UpgradeId } from "../../shared/core/upgrade-defs.ts";
import { wrapIndex } from "../../shared/platform/cyclic.ts";
import { tickDialogWithFallback } from "./dialog-tick.ts";

interface CreateUpgradePickDeps extends AutoResolveDeps {
  readonly state: GameState;
}

/** Per-entry auto-resolve tick. Dispatched by the runtime to the owning
 *  controller (`controller.tickUpgradePick`). Callers close over the
 *  per-call GameState and `autoDelaySeconds` when wrapping. */
type ControllerUpgradePickTick = (
  entry: UpgradePickEntry,
  entryIdx: number,
) => void;

/** Create the pick dialog from pre-generated offers on GameState.
 *  Offers were generated by generateUpgradeOffers() in prepareNextRound()
 *  using the synced RNG, so they're already deterministic.
 *  Returns null if picks are not applicable (classic mode, too early, no alive players). */
export function createUpgradePickDialog(
  deps: CreateUpgradePickDeps,
): UpgradePickDialogState | null {
  const { state } = deps;
  if (!state.modern?.pendingUpgradeOffers) return null;

  const entries: UpgradePickEntry[] = [];
  for (const [playerId, offers] of state.modern.pendingUpgradeOffers) {
    const autoResolve = shouldAutoResolve(playerId, deps);

    entries.push({
      playerId,
      offers,
      choice: null,
      autoResolve,
      autoTimer: 0,
      focusedCard: 0,
      pickedAtTimer: null,
    });
  }

  if (entries.length === 0) return null;
  return { entries, timer: 0 };
}

/** Tick the upgrade pick dialog.
 *
 *  Drives dialog-layer state only: increments `dialog.timer`, delegates
 *  each pending auto-resolve entry to the per-entry `tickEntry` callback,
 *  and delegates max-timer expiry to `forceResolve`. Both callbacks
 *  dispatch to the subsystem, which owns ownership routing (owner-funnel
 *  vs grace backstop) and the entry write.
 *
 *  Returns true when all entries are resolved.
 *
 *  @param dt — Delta time in seconds (not ms).
 *  @param maxTimer — Global force-resolve deadline in seconds.
 *  @param tickEntry — Per-entry tick (closed over state + autoDelay).
 *  @param forceResolve — Called every tick past `maxTimer` for each
 *    still-pending entry; must eventually resolve it. */
// Shares the auto-resolve + force-resolve loop with tickLifeLostDialog via tickDialogWithFallback.
export function tickUpgradePickDialog(
  dialog: UpgradePickDialogState,
  dt: number,
  maxTimer: number,
  tickEntry: ControllerUpgradePickTick,
  forceResolve: (entry: UpgradePickEntry) => void,
): boolean {
  return tickDialogWithFallback<UpgradePickEntry>({
    dialog,
    dt,
    maxTimer,
    isPending: (entry) => entry.choice === null,
    isAutoResolving: (entry) => entry.autoResolve,
    tickEntry: (entry, entryIdx) => {
      tickEntry(entry, entryIdx);
    },
    forceResolve,
  });
}

/** Navigate focus left/right within a pending entry's offers. */
export function moveUpgradePickFocus(
  entry: UpgradePickEntry,
  dir: number,
): void {
  entry.focusedCard = wrapIndex(entry.focusedCard, dir, entry.offers.length);
}

/** Apply a lockstep-scheduled upgrade pick to whichever peer's dialog
 *  state is live at drain time. Shared between originator and receiver
 *  so the apply behaves identically on every peer — mirrors
 *  `applyLifeLostChoiceToDialog` in life-lost-core.ts. The choice is
 *  untrusted wire data on the receiver, so membership in the entry's
 *  offers doubles as validation; a pick that lost the first-wins race
 *  (entry already resolved) or arrived with no dialog open is a silent
 *  no-op — the RECEIVER's schedule closure handles the no-dialog case by
 *  round-stamped early-queueing (see `handleUpgradePick` in
 *  online-server-events.ts). */
export function applyUpgradePickChoiceToDialog(
  playerId: ValidPlayerId,
  choice: string,
  dialog: UpgradePickDialogState | null,
): void {
  if (!dialog) return;
  const entry = dialog.entries.find((e) => e.playerId === playerId);
  if (!entry || entry.choice !== null) return;
  const cardIdx = entry.offers.findIndex((offer) => offer === choice);
  if (cardIdx < 0) return;
  resolveUpgradePickEntry(entry, cardIdx, dialog.timer);
}

/** Resolve a pending entry by picking a specific card. Returns the chosen upgrade. */
export function resolveUpgradePickEntry(
  entry: UpgradePickEntry,
  cardIdx: number,
  dialogTimer: number,
): UpgradeId {
  entry.focusedCard = cardIdx;
  const choice = entry.offers[cardIdx]!;
  entry.choice = choice;
  entry.pickedAtTimer = dialogTimer;
  return choice;
}
