/**
 * Upgrade pick dialog — create, tick, and resolve logic.
 * L3 (shared interfaces), mirrors life-lost.ts pattern.
 *
 * Pure functions operating on UpgradePickDialogState.
 * No runtime or rendering dependencies.
 */

import { GAME_MODE_MODERN } from "./game-constants.ts";
import type {
  GameState,
  UpgradePickDialogState,
  UpgradePickEntry,
} from "./types.ts";
import { IMPLEMENTED_UPGRADES, type UpgradeId } from "./upgrade-defs.ts";

interface CreateUpgradePickDeps {
  readonly state: GameState;
  readonly isHost: boolean;
  readonly myPlayerId: number;
  readonly remoteHumanSlots: ReadonlySet<number>;
  readonly isHumanController: (playerId: number) => boolean;
}

/** Number of upgrade choices offered per pick. */
const OFFER_COUNT = 3;
/** First round that triggers upgrade picks (modern mode). */
const UPGRADE_FIRST_ROUND = 3;
/** AI delay before auto-picking (seconds). */
export const UPGRADE_PICK_AI_DELAY = 1.5;
/** Max time before force-picking for pending players (seconds). */
export const UPGRADE_PICK_MAX_TIMER = 15;

/** Generate upgrade offers and create the pick dialog.
 *  Uses state.rng for deterministic online sync. Returns null if picks
 *  are not applicable (classic mode, too early, no alive players). */
/** Create the pick dialog from pre-generated offers on GameState.
 *  Offers were generated by generateUpgradeOffers() in enterBuildFromBattle()
 *  using the synced RNG, so they're already deterministic. */
export function createUpgradePickDialog(
  deps: CreateUpgradePickDeps,
): UpgradePickDialogState | null {
  const { state } = deps;
  if (!state.pendingUpgradeOffers) return null;

  const entries: UpgradePickEntry[] = [];
  for (const [playerId, offers] of state.pendingUpgradeOffers) {
    const isAi = deps.isHost
      ? !deps.isHumanController(playerId) &&
        !deps.remoteHumanSlots.has(playerId)
      : playerId !== deps.myPlayerId;

    entries.push({
      playerId,
      offers,
      choice: null,
      isAi,
      aiTimer: 0,
      focused: 0,
    });
  }

  if (entries.length === 0) return null;
  return { entries, timer: 0 };
}

/** Tick the upgrade pick dialog. AI players auto-pick after a delay.
 *  Returns the dialog (still active) or null (all resolved). */
export function tickUpgradePickDialog(
  dialog: UpgradePickDialogState,
  dt: number,
  aiDelay: number,
  maxTimer: number,
  state?: GameState,
): boolean {
  dialog.timer += dt;

  // AI auto-pick
  for (const entry of dialog.entries) {
    if (entry.choice !== null) continue;
    if (entry.isAi) {
      entry.aiTimer += dt;
      if (entry.aiTimer >= aiDelay) {
        entry.choice = aiPickUpgrade(entry.offers, entry.playerId, state);
      }
    }
  }

  // Max timer — force-pick for anyone still pending
  if (dialog.timer >= maxTimer) {
    for (const entry of dialog.entries) {
      if (entry.choice === null) {
        entry.choice = aiPickUpgrade(entry.offers, entry.playerId, state);
      }
    }
  }

  return dialog.entries.every((entry) => entry.choice !== null);
}

/** Apply all picked upgrades to player state. */
export function applyUpgradePicks(
  state: GameState,
  dialog: UpgradePickDialogState,
): void {
  for (const entry of dialog.entries) {
    if (entry.choice === null) continue;
    const player = state.players[entry.playerId];
    if (!player) continue;
    player.upgrades.set(entry.choice, 1);
  }
}

/** Generate upgrade offers for all alive players. Uses state.rng for determinism.
 *  Called from enterBuildFromBattle (game-engine layer) so the RNG is consumed
 *  before the BUILD_START checkpoint is sent. Returns null if not applicable. */
export function generateUpgradeOffers(
  state: GameState,
): Map<number, [UpgradeId, UpgradeId, UpgradeId]> | null {
  if (state.gameMode !== GAME_MODE_MODERN) return null;
  if (state.round < UPGRADE_FIRST_ROUND) return null;

  const offers = new Map<number, [UpgradeId, UpgradeId, UpgradeId]>();
  for (const player of state.players) {
    if (player.eliminated || !player.homeTower) continue;
    offers.set(player.id, drawOffers(state));
  }
  return offers.size > 0 ? offers : null;
}

/** Draw N unique upgrades from the implemented pool using state.rng. */
function drawOffers(state: GameState): [UpgradeId, UpgradeId, UpgradeId] {
  const pool = [...IMPLEMENTED_UPGRADES];
  const picked: UpgradeId[] = [];

  for (let i = 0; i < OFFER_COUNT && pool.length > 0; i++) {
    const totalWeight = pool.reduce((sum, def) => sum + def.weight, 0);
    let roll = state.rng.next() * totalWeight;
    let chosenIdx = pool.length - 1;
    for (let ci = 0; ci < pool.length; ci++) {
      roll -= pool[ci]!.weight;
      if (roll <= 0) {
        chosenIdx = ci;
        break;
      }
    }
    picked.push(pool[chosenIdx]!.id);
    pool.splice(chosenIdx, 1);
  }

  return picked as [UpgradeId, UpgradeId, UpgradeId];
}

/** AI picks a random offer using the synced RNG. */
function aiPickUpgrade(
  offers: readonly [UpgradeId, UpgradeId, UpgradeId],
  _playerId: number,
  state?: GameState,
): UpgradeId {
  if (!state) return offers[0];
  return offers[Math.floor(state.rng.next() * offers.length)]!;
}
