import type {
  UpgradePickDialogState,
  UpgradePickEntry,
} from "./dialog-types.ts";
import { type AutoResolveDeps, shouldAutoResolve } from "./player-config.ts";
import type { GameState } from "./types.ts";
import type { UpgradeId } from "./upgrade-defs.ts";

interface CreateUpgradePickDeps extends AutoResolveDeps {
  readonly state: GameState;
}

/** Auto-resolve delay before auto-picking (seconds). */
export const UPGRADE_PICK_AUTO_DELAY = 1.5;
/** Max time before force-picking for pending players (seconds). */
export const UPGRADE_PICK_MAX_TIMER = 15;

/** Generate upgrade offers and create the pick dialog.
 *  Uses state.rng for deterministic online sync. Returns null if picks
 *  are not applicable (classic mode, too early, no alive players). */
/** Create the pick dialog from pre-generated offers on GameState.
 *  Offers were generated by generateUpgradeOffers() in enterBuildFromBattle()
 *  using the synced RNG, so they're already deterministic. */
export function createUpgradePickDialog(
  deps: CreateUpgradePickDeps,
): UpgradePickDialogState | null {
  const { state } = deps;
  if (!state.modern?.pendingUpgradeOffers) return null;

  const entries: UpgradePickEntry[] = [];
  for (const [playerId, offers] of state.modern.pendingUpgradeOffers) {
    const autoResolve = shouldAutoResolve(playerId, deps);

    entries.push({
      playerId,
      offers,
      choice: null,
      autoResolve,
      autoTimer: 0,
      focusedCard: 0,
    });
  }

  if (entries.length === 0) return null;
  return { entries, timer: 0 };
}

/** Tick the upgrade pick dialog. Auto-resolve entries pick after a delay;
 *  max timer force-picks for all remaining entries.
 *  Returns true when all entries are resolved. */
// Parallel structure with tickLifeLostDialog (life-lost.ts) — both loop entries for auto-resolve + force-resolve.
export function tickUpgradePickDialog(
  dialog: UpgradePickDialogState,
  dt: number,
  autoDelay: number,
  maxTimer: number,
  state?: GameState,
): boolean {
  dialog.timer += dt;

  // Auto-resolve pending entries
  for (const entry of dialog.entries) {
    if (entry.choice !== null) continue;
    if (entry.autoResolve) {
      entry.autoTimer += dt;
      if (entry.autoTimer >= autoDelay) {
        entry.choice = randomPickUpgrade(entry.offers, state);
      }
    }
  }

  // Max timer — force-pick for anyone still pending
  if (dialog.timer >= maxTimer) {
    for (const entry of dialog.entries) {
      if (entry.choice === null) {
        entry.choice = randomPickUpgrade(entry.offers, state);
      }
    }
  }

  return dialog.entries.every((entry) => entry.choice !== null);
}

/** Apply all picked upgrades to player state. */
export function applyUpgradePicks(
  state: GameState,
  dialog: UpgradePickDialogState,
): void {
  for (const entry of dialog.entries) {
    if (entry.choice === null) continue;
    const player = state.players[entry.playerId];
    if (!player) continue;
    player.upgrades.set(entry.choice, 1);
  }
}

/** Pick a random offer using the synced RNG. */
function randomPickUpgrade(
  offers: readonly [UpgradeId, UpgradeId, UpgradeId],
  state?: GameState,
): UpgradeId {
  if (!state) return offers[0];
  return offers[Math.floor(state.rng.next() * offers.length)]!;
}
