/**
 * Upgrade pick dialog — create, tick, and resolve logic.
 * L3 (shared interfaces), mirrors life-lost.ts pattern.
 *
 * Pure functions operating on UpgradePickDialogState.
 * No runtime or rendering dependencies.
 */

import type {
  GameState,
  UpgradePickDialogState,
  UpgradePickEntry,
} from "./types.ts";
import { UPGRADE_POOL, type UpgradeId } from "./upgrade-defs.ts";

interface CreateUpgradePickDeps {
  readonly state: GameState;
  readonly isHost: boolean;
  readonly myPlayerId: number;
  readonly remoteHumanSlots: ReadonlySet<number>;
  readonly isHumanController: (playerId: number) => boolean;
}

/** Number of upgrade choices offered per pick. */
const OFFER_COUNT = 3;
/** First round that triggers upgrade picks (modern mode). */
const UPGRADE_FIRST_ROUND = 3;
/** AI delay before auto-picking (seconds). */
export const UPGRADE_PICK_AI_DELAY = 1.5;
/** Max time before force-picking for pending players (seconds). */
export const UPGRADE_PICK_MAX_TIMER = 15;

/** Generate upgrade offers and create the pick dialog.
 *  Uses state.rng for deterministic online sync. Returns null if picks
 *  are not applicable (classic mode, too early, no alive players). */
/** Create the pick dialog from pre-generated offers on GameState.
 *  Offers were generated by generateUpgradeOffers() in enterBuildFromBattle()
 *  using the synced RNG, so they're already deterministic. */
export function createUpgradePickDialog(
  deps: CreateUpgradePickDeps,
): UpgradePickDialogState | null {
  const { state } = deps;
  if (!state.pendingUpgradeOffers) return null;

  const entries: UpgradePickEntry[] = [];
  for (const [playerId, offers] of state.pendingUpgradeOffers) {
    const isAi = deps.isHost
      ? !deps.isHumanController(playerId) &&
        !deps.remoteHumanSlots.has(playerId)
      : playerId !== deps.myPlayerId;

    entries.push({
      playerId,
      offers,
      choice: null,
      isAi,
      aiTimer: 0,
      focused: 0,
    });
  }

  if (entries.length === 0) return null;
  return { entries, timer: 0 };
}

/** Tick the upgrade pick dialog. AI players auto-pick after a delay.
 *  Returns the dialog (still active) or null (all resolved). */
export function tickUpgradePickDialog(
  dialog: UpgradePickDialogState,
  dt: number,
  aiDelay: number,
  maxTimer: number,
  state?: GameState,
): boolean {
  dialog.timer += dt;

  // AI auto-pick
  for (const entry of dialog.entries) {
    if (entry.choice !== null) continue;
    if (entry.isAi) {
      entry.aiTimer += dt;
      if (entry.aiTimer >= aiDelay) {
        entry.choice = aiPickUpgrade(entry.offers, entry.playerId, state);
      }
    }
  }

  // Max timer — force-pick for anyone still pending
  if (dialog.timer >= maxTimer) {
    for (const entry of dialog.entries) {
      if (entry.choice === null) {
        entry.choice = aiPickUpgrade(entry.offers, entry.playerId, state);
      }
    }
  }

  return dialog.entries.every((entry) => entry.choice !== null);
}

/** Apply all picked upgrades to player state. */
export function applyUpgradePicks(
  state: GameState,
  dialog: UpgradePickDialogState,
): void {
  for (const entry of dialog.entries) {
    if (entry.choice === null) continue;
    const player = state.players[entry.playerId];
    if (!player) continue;
    const current = player.upgrades.get(entry.choice) ?? 0;
    player.upgrades.set(entry.choice, current + 1);
  }
}

/** Generate upgrade offers for all alive players. Uses state.rng for determinism.
 *  Called from enterBuildFromBattle (game-engine layer) so the RNG is consumed
 *  before the BUILD_START checkpoint is sent. Returns null if not applicable. */
export function generateUpgradeOffers(
  state: GameState,
): Map<number, [UpgradeId, UpgradeId, UpgradeId]> | null {
  if (state.gameMode !== "modern") return null;
  if (state.round < UPGRADE_FIRST_ROUND) return null;

  const offers = new Map<number, [UpgradeId, UpgradeId, UpgradeId]>();
  for (const player of state.players) {
    if (player.eliminated || !player.homeTower) continue;
    offers.set(player.id, drawOffers(state));
  }
  return offers.size > 0 ? offers : null;
}

/** Draw N unique upgrades from the weighted pool using state.rng. */
function drawOffers(state: GameState): [UpgradeId, UpgradeId, UpgradeId] {
  const available = [...UPGRADE_POOL];
  const picked: UpgradeId[] = [];

  for (let i = 0; i < OFFER_COUNT && available.length > 0; i++) {
    const totalWeight = available.reduce((sum, def) => sum + def.weight, 0);
    let roll = state.rng.next() * totalWeight;
    let chosenIdx = available.length - 1;
    for (let ci = 0; ci < available.length; ci++) {
      roll -= available[ci]!.weight;
      if (roll <= 0) {
        chosenIdx = ci;
        break;
      }
    }
    picked.push(available[chosenIdx]!.id);
    available.splice(chosenIdx, 1);
  }

  return picked as [UpgradeId, UpgradeId, UpgradeId];
}

/** AI picks the highest-scored offer. Falls back to first offer if no state. */
function aiPickUpgrade(
  offers: readonly [UpgradeId, UpgradeId, UpgradeId],
  playerId: number,
  state?: GameState,
): UpgradeId {
  if (!state) return offers[0];

  const player = state.players[playerId];
  if (!player) return offers[0];

  // Count grunts targeting this player
  const gruntCount = state.grunts.filter(
    (gr) => gr.targetPlayerId === playerId,
  ).length;

  // Territory ratio: how much of the zone this player controls (0-1)
  const totalGrass = 200; // rough estimate, avoids scanning the full map
  const territoryRatio = Math.min(1, player.interior.size / totalGrass);

  let bestId = offers[0];
  let bestScore = -1;
  for (const id of offers) {
    const sc = scoreUpgrade(id, player, gruntCount, territoryRatio);
    if (sc > bestScore) {
      bestScore = sc;
      bestId = id;
    }
  }
  return bestId;
}

/** Score an upgrade for a given player based on game context. Higher = better. */
function scoreUpgrade(
  id: UpgradeId,
  player: {
    id: number;
    cannons: { length: number };
    interior: ReadonlySet<number>;
    upgrades: Map<UpgradeId, number>;
  },
  gruntCount: number,
  territoryRatio: number,
): number {
  const has = (uid: UpgradeId) => (player.upgrades.get(uid) ?? 0) > 0;

  switch (id) {
    // Defensive — valuable when under grunt pressure or small territory
    case "reinforced_walls":
      return has("reinforced_walls") ? 1 : 5 + gruntCount * 2;
    case "master_builder":
      return 4 + (1 - territoryRatio) * 6;
    case "foundations":
      return has("foundations") ? 1 : 3;
    case "large_pieces":
      return has("large_pieces") ? 1 : 4;

    // Offensive — valuable when the player has many cannons
    case "rapid_fire":
      return 3 + player.cannons.length * 1.5;
    case "scatter_shot":
      return has("scatter_shot") ? 1 : 3 + player.cannons.length;
    case "mortar":
      return has("mortar") ? 1 : 4;
    case "flaming_walls":
      return has("flaming_walls") ? 1 : 3;

    // Strategic
    case "scout_tower":
      return has("scout_tower") ? 1 : 3;
    case "mercenaries":
      return 4;
    case "fortify":
      return 2 + gruntCount;
    case "salvage":
      return has("salvage") ? 1 : 3;

    // One-use
    case "earthquake":
      return 3;
    case "ceasefire":
      return territoryRatio < 0.3 ? 6 : 2;
    case "supply_drop":
      return 4;

    default:
      return 3;
  }
}
